const DEFAULT_DOMAIN = 'pdf.itea.fit'
const DEFAULT_PAGES_PROJECT = 'pdf-inspector-web'
const DEFAULT_PRODUCTION_BRANCH = 'main'

export const CLOUDFLARE_PAGES_DOMAIN =
  process.env.CLOUDFLARE_PAGES_DOMAIN || DEFAULT_DOMAIN

export const CLOUDFLARE_PAGES_PROJECT_NAME =
  process.env.CLOUDFLARE_PAGES_PROJECT_NAME || DEFAULT_PAGES_PROJECT

export const CLOUDFLARE_PAGES_PRODUCTION_BRANCH =
  process.env.CLOUDFLARE_PAGES_PRODUCTION_BRANCH || DEFAULT_PRODUCTION_BRANCH

export const SITE_ORIGIN = `https://${CLOUDFLARE_PAGES_DOMAIN}`
